language: generic
sudo: require
services:
    - docker

before install:
    - docker build -t str8y/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true str8y/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-eu-central-1-823520998717"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
