language: generic
sudo: require
services:
    - docker

before install:
    - docker build -t str8y/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true str8y/docker-react npm run test